spring:
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,httptrace,mappings,scheduledtasks,threaddump,heapdump
  info:
    git:
      mode: full

optaplanner:
  solverConfigXml: com/github/invest/investmentSolverConfig.xml