name: Java CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master
jobs:
  gradle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setting up JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Log into Dockerhub (optional)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Running gradle task
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: clean assembleBootServerAndClient dockerTag dockerTag dockerTagsPush
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: opta-invest jar
          path: build/app.jar